name: Deploy via SFTP

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: FTP_SERVER   # <- yahan aapka environment name
 
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Upload files via SFTP
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          port: ${{ secrets.FTP_PORT }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local_path: './*'
          remote_path: '/var/www/consumeraffairs'
          sftp_only: true
          delete_remote_files: false
